// src/app/lib/servicesData.js
// Full content for every individual certification service detail page.
// Consumed by src/app/screens/ServiceDetailScreen.jsx and the per-service
// route folders (bis/, epr/, wpc/, tec/, bee/, lmpc/, iso/, cdsco/).

export const SERVICE_DETAILS = {
  bis: {
    slug: 'bis',
    icon: '🏷️',
    title: 'BIS Certification',
    subtitle: 'Bureau of Indian Standards',
    heroImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1600&q=85&fit=crop',
    heroChips: ['ISI Mark', 'CRS Registration', 'Scheme-X', 'Hallmarking', '0% Failure Rate'],
    intro: 'Mandatory quality certification by the Bureau of Indian Standards. Whether you need ISI Mark, CRS Registration, or Scheme-X for foreign manufacturers — we handle it all end-to-end.',
    introSecondary: 'Our BIS specialists coordinate with BIS-recognized labs, prepare your complete application, manage factory inspections, and follow up until your license is in hand.',
    quickInfo: [
      { label: 'Applicable Products', value: '370+ Categories' },
      { label: 'Governing Body', value: 'Bureau of Indian Standards' },
      { label: 'Validity', value: '1–2 Years (Renewable)' },
      { label: 'Typical Timeline', value: '4–12 Weeks' },
      { label: 'Our Failure Rate', value: '0%' },
    ],
    stats: [
      { value: '370+', label: 'Product Categories', icon: '📋' },
      { value: '4–12', label: 'Weeks Timeline', icon: '⚡' },
      { value: 'Free', label: 'Initial Consultation', icon: '🆓' },
      { value: '0%', label: 'Failure Rate', icon: '❌' },
    ],
    types: [
      { icon: '🔖', title: 'BIS ISI Mark', tag: 'Manufacturing', desc: 'Mandatory for 370+ product categories including steel, cement, electrical goods, and more sold in India.' },
      { icon: '📱', title: 'BIS CRS Registration', tag: 'Electronics', desc: 'Compulsory Registration Scheme for 70+ electronic & IT products like laptops, mobiles, LED lights, chargers.' },
      { icon: '🌍', title: 'BIS Scheme-X', tag: 'Foreign Manufacturers', desc: 'Specially designed for overseas manufacturers who want to sell BIS-certified products directly in India.' },
      { icon: '💍', title: 'BIS Hallmarking', tag: 'Jewellery', desc: 'Mandatory gold and silver hallmarking certification under BIS for all jewellers across India.' },
      { icon: '🌿', title: 'ECO Mark', tag: 'Environment', desc: 'Eco-friendly product certification for manufacturers committed to environmental standards.' },
      { icon: '🏭', title: 'FMCS Certification', tag: 'Industrial', desc: 'Foreign Manufacturers Certification Scheme for industrial products from overseas companies.' },
    ],
    process: [
      { step: '01', icon: '🔍', title: 'Product Assessment', desc: 'We identify the exact BIS scheme applicable to your product and the relevant Indian Standard (IS) number.' },
      { step: '02', icon: '🧪', title: 'Lab Testing', desc: 'Product samples are tested at a BIS-recognized lab. We coordinate with labs to get results quickly.' },
      { step: '03', icon: '📤', title: 'Document Filing', desc: 'Complete application with test reports and all required documents is filed with BIS on your behalf.' },
      { step: '04', icon: '🎓', title: 'Grant of License', desc: 'BIS reviews and approves your application. License / Registration Certificate is issued.' },
    ],
    documents: [
      { icon: '🧪', title: 'Product Test Report', desc: 'From a BIS-recognized laboratory, tested against the applicable Indian Standard (IS) number.' },
      { icon: '🏭', title: 'Factory / Premises Details', desc: 'Address proof and layout plan for the manufacturing unit (required for ISI Mark applications).' },
      { icon: '📐', title: 'Product Specifications', desc: 'Technical drawings and datasheets describing the product covered under the application.' },
      { icon: '🏢', title: 'Company Registration', desc: 'Certificate of Incorporation, GST registration, and authorized signatory KYC documents.' },
      { icon: '🚢', title: 'Import-Export Code', desc: 'IEC certificate, required for CRS and Scheme-X applications by importers.' },
      { icon: '📘', title: 'Quality Manual', desc: 'Required for ISI Mark applicants as part of the factory inspection process.' },
    ],
    faqs: [
      { q: 'Which products require BIS CRS registration?', a: '70+ products including mobile phones, laptops, tablets, LED lights, power banks, chargers, set-top boxes, smart watches, and more require mandatory CRS registration.' },
      { q: 'How long does BIS CRS registration take?', a: 'Typically 4–8 weeks if all documents are in order and lab test reports are available. We help expedite the process.' },
      { q: 'Can a foreign company apply for BIS certification?', a: 'Yes, through BIS Scheme-X or the Foreign Manufacturers Certification Scheme (FMCS). An Indian Authorized Representative (IAR) is required.' },
      { q: 'What happens if I sell products without BIS certification?', a: 'Products sold without mandatory BIS certification can be seized, and the company faces heavy penalties and import bans under the BIS Act, 2016.' },
      { q: 'Is BIS certification valid permanently?', a: 'No. ISI Mark licenses are valid for 1–2 years and must be renewed. CRS registrations are valid for 2 years.' },
    ],
  },

  'bis-crs': {
    slug: 'bis-crs',
    icon: '📱',
    title: 'BIS CRS Registration',
    subtitle: 'Compulsory Registration Scheme',
    heroImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1600&q=85&fit=crop',
    heroChips: ['Mobiles & Laptops', 'LED Lights', 'Power Banks', 'R-Number', '0% Failure Rate'],
    intro: 'Mandatory registration for 70+ electronics & IT products — mobile phones, laptops, LED lights, chargers, power banks, and set-top boxes. No factory inspection required, so approval is faster than ISI Mark.',
    introSecondary: 'Our BIS specialists identify the applicable IS standard, coordinate testing at a BIS-recognized lab, and file the complete CRS application on the BIS portal until your R-number is granted.',
    quickInfo: [
      { label: 'Applicable Products', value: '70+ Categories' },
      { label: 'Governing Body', value: 'Bureau of Indian Standards' },
      { label: 'Validity', value: '2 Years (Renewable)' },
      { label: 'Typical Timeline', value: '4–8 Weeks' },
      { label: 'Factory Inspection', value: 'Not Required' },
    ],
    stats: [
      { value: '70+', label: 'Product Categories', icon: '📋' },
      { value: '4–8', label: 'Weeks Timeline', icon: '⚡' },
      { value: 'Free', label: 'Initial Consultation', icon: '🆓' },
      { value: '0%', label: 'Failure Rate', icon: '❌' },
    ],
    types: [
      { icon: '📱', title: 'Mobile Phones & Tablets', tag: 'Mandatory', desc: 'All mobile phones, smartphones, and tablets sold in India require BIS CRS registration before import or sale.' },
      { icon: '💻', title: 'Laptops & Notebooks', tag: 'Mandatory', desc: 'Laptops, notebooks, and portable computers require CRS registration under the Electronics & IT goods category.' },
      { icon: '💡', title: 'LED Lights & Luminaires', tag: 'Mandatory', desc: 'LED lamps, LED light engines and LED luminaires must be CRS registered before they enter the Indian market.' },
      { icon: '🔌', title: 'Chargers & Power Adapters', tag: 'Mandatory', desc: 'Mobile chargers, laptop adapters and USB power adapters all require mandatory CRS registration.' },
      { icon: '🔋', title: 'Power Banks', tag: 'Mandatory', desc: 'Portable rechargeable battery packs (power banks) are covered under the mandatory CRS scheme.' },
      { icon: '📺', title: 'Set-Top Boxes & Smart TVs', tag: 'Mandatory', desc: 'Set-top boxes, smart televisions and display panels fall under the mandatory CRS electronics category.' },
    ],
    process: [
      { step: '01', icon: '🔍', title: 'Product Identification', desc: 'We confirm if your product falls under the mandatory CRS list and identify the applicable IS standard.' },
      { step: '02', icon: '🧪', title: 'Lab Testing', desc: 'Product samples are tested at a BIS-recognized lab. We coordinate with labs to minimize turnaround time.' },
      { step: '03', icon: '📤', title: 'BIS Portal Application', desc: 'We prepare and file the complete CRS application on the BIS portal with test reports and all required documents.' },
      { step: '04', icon: '🔎', title: 'BIS Review', desc: 'BIS reviews the application and test reports. We track the status and respond to any queries from BIS.' },
    ],
    documents: [
      { icon: '📄', title: 'Test Report', desc: 'Valid test report from a BIS-recognized laboratory confirming compliance with the applicable IS standard.' },
      { icon: '🏢', title: 'Company Registration', desc: "Importer or manufacturer's certificate of incorporation, partnership deed, or proprietorship proof." },
      { icon: '🚢', title: 'Import-Export Code (IEC)', desc: 'IEC certificate issued by DGFT — mandatory for all importers applying for CRS registration.' },
      { icon: '👤', title: 'AIR Details (Foreign Brands)', desc: 'Authorized Indian Representative (AIR) appointment letter and KYC documents. Required for all foreign manufacturers.' },
      { icon: '📐', title: 'Product Specification Sheet', desc: 'Detailed technical datasheet describing product specifications, model numbers, and electrical parameters.' },
      { icon: '🔖', title: 'Brand Authorization Letter', desc: 'If the applicant is not the original brand owner, a brand authorization letter from the brand holder is required.' },
    ],
    faqs: [
      { q: 'Which products require BIS CRS registration?', a: '70+ products including mobile phones, laptops, tablets, LED lights, power banks, chargers, set-top boxes, smart watches, and more require mandatory CRS registration under the Electronics & IT Goods Order.' },
      { q: 'How long does BIS CRS registration take?', a: 'Typically 4–8 weeks if all documents are in order and lab test reports are available. We help expedite the process with our lab network.' },
      { q: 'Can a foreign company apply for BIS CRS directly?', a: 'Yes. Foreign manufacturers can apply through an Authorized Indian Representative (AIR). Our team can act as your AIR or guide you through the appointment process.' },
      { q: 'What is the validity of a BIS CRS registration?', a: 'BIS CRS registrations are valid for 2 years and must be renewed before expiry to continue selling in India legally.' },
      { q: 'What happens if I sell products without CRS registration?', a: 'Products sold without mandatory BIS CRS registration can be seized at customs or in the market, with heavy penalties under the BIS Act, 2016 and a possible import ban.' },
    ],
  },

  'bis-isi': {
    slug: 'bis-isi',
    icon: '🔖',
    title: 'BIS ISI Mark',
    subtitle: 'Bureau of Indian Standards',
    heroImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1600&q=85&fit=crop',
    heroChips: ['370+ Categories', 'Factory Inspection', 'CM/L License', 'Steel & Electrical', '0% Failure Rate'],
    intro: 'Mandatory quality certification for 370+ product categories including steel, cement, electrical goods, and safety equipment sold in India. A stamped mark backed by factory inspection and ongoing surveillance.',
    introSecondary: 'Our BIS specialists prepare your Quality Manual and factory documentation, coordinate lab testing, and manage the BIS factory inspection until your CM/L license is granted.',
    quickInfo: [
      { label: 'Applicable Products', value: '370+ Categories' },
      { label: 'Governing Body', value: 'Bureau of Indian Standards' },
      { label: 'Validity', value: '1–2 Years (Renewable)' },
      { label: 'Typical Timeline', value: '8–12 Weeks' },
      { label: 'Factory Inspection', value: 'Required' },
    ],
    stats: [
      { value: '370+', label: 'Product Categories', icon: '📋' },
      { value: '8–12', label: 'Weeks Timeline', icon: '⚡' },
      { value: 'Free', label: 'Initial Consultation', icon: '🆓' },
      { value: '0%', label: 'Failure Rate', icon: '❌' },
    ],
    types: [
      { icon: '🔩', title: 'Steel & Iron Products', tag: 'Industrial', desc: 'Reinforcement bars, mild steel tubes, galvanized steel sheets and structural steel sections all require ISI Mark certification.' },
      { icon: '🏗️', title: 'Cement & Building Materials', tag: 'Construction', desc: 'Portland cement, fly ash bricks, ceramic tiles, sanitary ware and building hardware require mandatory ISI certification.' },
      { icon: '⚡', title: 'Electrical Goods', tag: 'Electrical', desc: 'Domestic wiring cables, switches, plug sockets, MCBs, transformers and electrical motors require mandatory ISI Mark.' },
      { icon: '🍳', title: 'Pressure Cookers & Cookware', tag: 'Consumer', desc: 'Pressure cookers, cylinders, and LPG-related products must carry the ISI Mark before being sold in India.' },
      { icon: '🚰', title: 'Water Pipes & Fittings', tag: 'Plumbing', desc: 'PVC pipes, CPVC fittings, water meters, and related plumbing materials require ISI certification for quality assurance.' },
      { icon: '🪖', title: 'Safety Equipment', tag: 'Safety', desc: 'Helmets (industrial and two-wheeler), safety shoes, fire extinguishers, and protective gear require mandatory ISI Mark.' },
    ],
    process: [
      { step: '01', icon: '🔍', title: 'IS Standard & Scheme Identification', desc: 'We identify the exact Indian Standard (IS number) applicable to your product and confirm whether ISI Mark is mandatory under the relevant Quality Control Order.' },
      { step: '02', icon: '🧪', title: 'Product Sample Testing', desc: 'Product samples are tested at a BIS-recognized lab against the full test parameters of the applicable IS standard.' },
      { step: '03', icon: '📋', title: 'Quality Manual & Factory Docs', desc: 'We prepare the Quality Manual, manufacturing process flowcharts, raw material supplier list, and factory layout plan.' },
      { step: '04', icon: '📤', title: 'BIS Portal Application', desc: 'We file the complete ISI Mark license application on the BIS portal with test reports, Quality Manual, and company documents.' },
      { step: '05', icon: '🔎', title: 'BIS Factory Inspection', desc: 'A BIS officer inspects your facility, equipment, raw material quality, production process, and in-process quality controls.' },
      { step: '06', icon: '🎓', title: 'License Grant & CM/L Stamping', desc: 'BIS issues the ISI Mark License with a unique CM/L number. Products can then be stamped with the ISI Mark for sale.' },
    ],
    documents: [
      { icon: '📄', title: 'Product Test Report', desc: 'Valid test report from a BIS-recognized laboratory confirming compliance with the applicable IS standard for the product.' },
      { icon: '🏭', title: 'Factory Premises Proof', desc: 'Factory lease agreement or ownership document, layout plan, and address proof of the manufacturing unit.' },
      { icon: '🏢', title: 'Company Registration Certificate', desc: 'Certificate of Incorporation, Partnership Deed, or Proprietorship registration as applicable to the business entity.' },
      { icon: '📘', title: 'Quality Manual', desc: 'Comprehensive Quality Manual aligned with the applicable Indian Standard — covering production, quality checks, and testing.' },
      { icon: '🔄', title: 'Manufacturing Process Flowchart', desc: 'Detailed flow diagram of the manufacturing process from raw material intake to finished product dispatch.' },
      { icon: '🪪', title: 'Authorized Signatory KYC', desc: 'PAN card, Aadhaar, and authorization letter for the person signing the BIS application on behalf of the company.' },
    ],
    faqs: [
      { q: 'Which products require mandatory ISI Mark in India?', a: '370+ product categories require mandatory ISI Mark including steel, cement, electrical goods (cables, switches, MCBs), LPG cylinders, pressure cookers, helmets, and many more under the BIS Act, 2016.' },
      { q: 'How is ISI Mark different from BIS CRS?', a: 'ISI Mark is a physical mark stamped on manufactured goods after factory inspection. BIS CRS is a registration scheme for specific electronics/IT goods that only needs an R-number, without a stamped mark or inspection.' },
      { q: 'How long does ISI Mark certification take?', a: 'Typically 8–12 weeks depending on the product, lab test availability, and factory inspection scheduling. Our team tracks every stage to avoid unnecessary delays.' },
      { q: 'Can a foreign manufacturer get ISI Mark?', a: 'Yes. Foreign manufacturers can apply under BIS Scheme-X or the Foreign Manufacturers Certification Scheme (FMCS). An Indian Authorized Representative (IAR) is required.' },
      { q: 'How long is an ISI Mark license valid?', a: 'ISI Mark licenses are typically valid for 1–2 years and must be renewed before expiry, with annual surveillance audits conducted by BIS during the license period.' },
    ],
  },

  testing: {
    slug: 'testing',
    icon: '🔬',
    title: 'Testing & Certification',
    subtitle: 'Lab Coordination & Compliance Testing',
    heroImage: 'https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=1600&q=85&fit=crop',
    heroChips: ['Product Safety Testing', 'EMC / RF Testing', 'Chemical Testing', 'Environmental Testing', '0% Failure Rate'],
    intro: 'Lab coordination for every Indian certification — BIS CRS, ISI Mark, WPC-ETA, TEC MTCTE, and BEE. We identify the right accredited lab and standard so your test report is accepted the first time.',
    introSecondary: 'Our specialists scope the applicable standard, select the right NABL / BIS / WPC / TEC-accredited lab, plan samples, and track testing end-to-end until the report is ready for filing.',
    quickInfo: [
      { label: 'Lab Type', value: 'NABL / BIS / TEC / WPC' },
      { label: 'Standards', value: 'IS, IEC, EN, IEEE & more' },
      { label: 'Turnaround', value: '1–12 Weeks (product-based)' },
      { label: 'Reports Valid For', value: 'BIS, WPC, TEC, BEE filings' },
      { label: 'Our Failure Rate', value: '0%' },
    ],
    stats: [
      { value: '50+', label: 'Accredited Labs', icon: '🏛️' },
      { value: '1–12', label: 'Weeks Turnaround', icon: '⚡' },
      { value: 'Free', label: 'Initial Consultation', icon: '🆓' },
      { value: '0%', label: 'Failure Rate', icon: '❌' },
    ],
    types: [
      { icon: '🔬', title: 'Product Safety Testing', tag: 'Mandatory', desc: 'Safety and performance testing for consumer electronics, electrical appliances, and industrial products as per Indian standards.' },
      { icon: '📡', title: 'EMC / RF Testing', tag: 'Wireless Devices', desc: 'Electromagnetic Compatibility and Radio Frequency testing for wireless, Bluetooth, Wi-Fi, and IoT devices.' },
      { icon: '⚗️', title: 'Chemical & Material Testing', tag: 'FMCG / Pharma', desc: 'Lab testing for chemicals, raw materials, food products, and pharmaceutical formulations for compliance and safety.' },
      { icon: '🏗️', title: 'Mechanical & Structural Testing', tag: 'Industrial', desc: 'Strength, durability, and structural integrity testing for construction materials, industrial components, and machinery.' },
      { icon: '🌿', title: 'Environmental Testing', tag: 'Sustainability', desc: 'RoHS, REACH, and environmental compliance testing for electronics, plastics, and consumer goods.' },
      { icon: '🧴', title: 'Consumer Product Testing', tag: 'Retail', desc: 'Comprehensive testing for toys, cosmetics, textiles, footwear, and packaged food products.' },
    ],
    process: [
      { step: '01', icon: '🔍', title: 'Product Scoping & Standard ID', desc: 'We identify the applicable Indian Standard and confirm the exact test scope your product needs.' },
      { step: '02', icon: '🏛️', title: 'Lab Selection & Sample Planning', desc: 'We benchmark accredited labs for cost and turnaround, and plan the samples required for testing.' },
      { step: '03', icon: '📦', title: 'Sample Submission & Coordination', desc: 'Samples are submitted to the selected lab and we coordinate every step of the intake process.' },
      { step: '04', icon: '⏱️', title: 'Active Testing Monitoring', desc: 'We track testing progress with the lab and flag issues early to avoid last-minute delays.' },
      { step: '05', icon: '✅', title: 'Report Review & Validation', desc: 'Test reports are reviewed for accuracy and completeness before being used for certification filing.' },
      { step: '06', icon: '📤', title: 'Certification Filing & Closure', desc: 'Validated reports are filed with BIS, WPC, TEC, or BEE as applicable to close out your certification.' },
    ],
    documents: [
      { icon: '📄', title: 'Product Technical Datasheet', desc: 'Detailed technical specification sheet covering product category, model number, electrical ratings, and materials.' },
      { icon: '📦', title: 'Product Samples', desc: 'Production-representative samples as specified by the applicable lab and standard — typically 3 to 10 units.' },
      { icon: '📘', title: 'User Manual / Product Brochure', desc: 'User manual or brochure describing product features, operating parameters, and safety instructions in English.' },
      { icon: '📐', title: 'Circuit Diagram / Block Diagram', desc: "Schematic of the product's electrical or electronic design — mandatory for electronics, appliances, and wireless devices." },
      { icon: '🏢', title: 'Company Registration & KYC', desc: 'Certificate of Incorporation or equivalent business registration, along with KYC of the authorized signatory.' },
      { icon: '🔖', title: 'Applicable IS / Standard Number', desc: 'The specific Indian Standard or international standard number applicable to your product.' },
    ],
    faqs: [
      { q: 'Which lab should I use for BIS CRS certification?', a: 'You must use a BIS-recognized lab for CRS registration. We maintain partnerships with multiple BIS-recognized labs across India and help coordinate the fastest turnaround for your product category.' },
      { q: 'How many product samples are needed for testing?', a: 'The number of samples varies by product and standard — typically 3 to 10 units. We advise you on exact requirements based on your specific product and applicable Indian Standard.' },
      { q: 'Can I use a foreign test report for Indian certifications?', a: 'In some cases, yes. BIS CRS and certain TEC/WPC approvals accept test reports from internationally accredited labs (ILAC-MRA members). We can assess if your existing report qualifies.' },
      { q: 'How long does product testing take?', a: 'Testing timelines vary: 1–2 weeks for simple consumer products, 3–6 weeks for electronics with EMC testing, and up to 8–12 weeks for complex telecom equipment.' },
      { q: 'What happens if my product fails the test?', a: 'We help identify the root cause of failure, recommend design or compliance fixes, and coordinate re-testing efficiently.' },
    ],
  },

  epr: {
    slug: 'epr',
    icon: '♻️',
    title: 'EPR Registration',
    subtitle: 'Extended Producer Responsibility',
    heroImage: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=1600&q=85&fit=crop',
    heroChips: ['E-Waste EPR', 'Plastic Waste EPR', 'Battery EPR', 'CPCB Filing', '0% Failure Rate'],
    intro: 'E-waste, plastics, and battery EPR registration with CPCB. Full documentation, PRO empanelment, and annual compliance reporting for producers, importers, and brand owners.',
    introSecondary: 'Our EPR specialists prepare your CPCB portal filing, connect you with empanelled Producer Responsibility Organizations, and manage every annual return so you never miss a deadline.',
    quickInfo: [
      { label: 'Governing Body', value: 'CPCB / MoEFCC' },
      { label: 'Applicable To', value: 'Producers, Importers, Brand Owners' },
      { label: 'Validity', value: 'Annual (Renewable)' },
      { label: 'Processing Time', value: '3–6 Weeks' },
      { label: 'Penalty for Default', value: 'Up to ₹1L / day' },
    ],
    stats: [
      { value: 'Annual', label: 'Renewal Cycle', icon: '📅' },
      { value: '3–6', label: 'Weeks Timeline', icon: '⚡' },
      { value: 'Free', label: 'Initial Consultation', icon: '🆓' },
      { value: '0%', label: 'Failure Rate', icon: '❌' },
    ],
    types: [
      { icon: '💻', title: 'EPR for E-Waste', tag: 'Mandatory', desc: 'For producers, importers & brand owners of electrical & electronic equipment under E-Waste Management Rules, 2022.' },
      { icon: '🧴', title: 'EPR for Plastic Waste', tag: 'Mandatory', desc: 'For producers, importers & brand owners using plastic packaging under Plastic Waste Management Rules.' },
      { icon: '🔋', title: 'EPR for Battery Waste', tag: 'Mandatory', desc: 'For manufacturers and importers of batteries — lithium-ion, lead acid, and all battery types under Battery Waste Management Rules, 2022.' },
      { icon: '🚗', title: 'EPR for Tyre Waste', tag: 'Mandatory', desc: 'For tyre manufacturers and importers under the Hazardous & Other Wastes Management Rules.' },
      { icon: '🛢️', title: 'EPR for Used Oil', tag: 'Mandatory', desc: 'For producers and importers of lubricating oils and other petroleum-based products under Hazardous Waste Rules.' },
      { icon: '📄', title: 'CPCB Authorization', tag: 'Compliance', desc: 'General CPCB authorization and No Objection Certificate for waste-related compliance and storage facilities.' },
    ],
    process: [
      { step: '01', icon: '📋', title: 'Category Assessment', desc: 'We identify which EPR category (e-waste, plastic, battery) applies to your product portfolio.' },
      { step: '02', icon: '📝', title: 'Portal Filing', desc: 'We prepare and file your complete registration on the CPCB EPR portal, including HS codes and sales volumes.' },
      { step: '03', icon: '🤝', title: 'PRO Empanelment', desc: 'We connect you with a CPCB-empanelled Producer Responsibility Organization to meet your collection targets.' },
      { step: '04', icon: '✅', title: 'Registration & Filing', desc: 'CPCB issues your EPR registration; we then manage your annual compliance returns going forward.' },
    ],
    documents: [
      { icon: '🏢', title: 'Company Registration Certificate', desc: 'Certificate of Incorporation, LLP registration, or equivalent business registration document.' },
      { icon: '🔖', title: 'GST Registration Certificate', desc: 'Mandatory for all applicants; the registered business name must match the CPCB portal details.' },
      { icon: '📦', title: 'Product & Sales Volume Data', desc: 'Category-wise product list with annual production/import volumes for EPR target calculation.' },
      { icon: '🚢', title: 'Import-Export Code (IEC)', desc: 'Valid IEC issued by DGFT — mandatory for all importers filing EPR under any category.' },
      { icon: '🏷️', title: 'HS Codes for All Products', desc: 'Harmonized System codes for each product category covered under the EPR application.' },
      { icon: '📜', title: 'Board Resolution', desc: 'Authorizing the company to apply for EPR registration and designating the signatory.' },
    ],
    faqs: [
      { q: 'Who needs EPR Registration?', a: 'Any producer, importer, or brand owner (PIBOs) dealing in electronics, plastic packaging, batteries, tyres, or used oil in India must register under EPR. Non-compliance can result in heavy CPCB penalties.' },
      { q: 'What is the penalty for non-compliance?', a: 'CPCB can impose penalties, cancel import licenses, and initiate legal proceedings. Penalties can go up to ₹1 lakh per day of non-compliance — making timely registration essential.' },
      { q: 'What is a PRO and do I need one?', a: 'A Producer Responsibility Organization (PRO) helps you fulfill your EPR collection targets. Most businesses need to tie up with a CPCB-empanelled PRO. We connect you with the right partners.' },
      { q: 'How often do I need to file EPR returns?', a: 'Annual returns are mandatory. You must report your collection, recycling and disposal data to CPCB every financial year. We assist with all annual filings and compliance tracking.' },
      { q: 'How long does EPR registration take?', a: 'Typically 3–6 weeks from the time all documents are submitted to CPCB. We actively track and follow up to ensure your registration is issued without delays.' },
    ],
  },

  wpc: {
    slug: 'wpc',
    icon: '📡',
    title: 'WPC — ETA Approval',
    subtitle: 'Wireless Planning & Coordination Wing',
    heroImage: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1600&q=85&fit=crop',
    heroChips: ['WPC-ETA Approval', 'Import License', 'DPL / NDPL', 'Equipment Type Approval', '0% Failure Rate'],
    intro: 'Mandatory for Wi-Fi, Bluetooth, GPS, RFID, and all wireless devices. We manage lab testing with accredited labs and WPC portal submissions for Equipment Type Approval.',
    introSecondary: 'Our WPC specialists prepare your RF test coordination, file your Saral Sanchar portal application, and follow up with the WPC Wing until your ETA is granted.',
    quickInfo: [
      { label: 'Governing Body', value: 'WPC Wing, DoT' },
      { label: 'Portal', value: 'Saralsanchar.gov.in' },
      { label: 'Validity', value: '5 Years' },
      { label: 'Processing Time', value: '4–8 Weeks' },
      { label: 'Applicable To', value: 'Wi-Fi, BT, RF Devices' },
    ],
    stats: [
      { value: '5 yrs', label: 'Approval Validity', icon: '📅' },
      { value: '4–8', label: 'Weeks Timeline', icon: '⚡' },
      { value: 'Free', label: 'Initial Consultation', icon: '🆓' },
      { value: '0%', label: 'Failure Rate', icon: '❌' },
    ],
    types: [
      { icon: '📡', title: 'WPC-ETA Approval', tag: 'Import Mandatory', desc: 'Equipment Type Approval for importing wireless devices with Bluetooth, Wi-Fi, Zigbee, or RF frequency bands.' },
      { icon: '📋', title: 'WPC Import License', tag: 'Commercial Import', desc: 'Required for commercial import of wireless telecom equipment into India under WPC norms.' },
      { icon: '📻', title: 'DPL / NDPL License', tag: 'Possession', desc: 'Demonstration Purpose License and Non-Demonstration Purpose License for RF devices.' },
      { icon: '🔬', title: 'Equipment Type Approval', tag: 'Testing', desc: 'Type approval for telecom equipment submitted for testing and approval under DoT guidelines.' },
    ],
    process: [
      { step: '01', icon: '🔍', title: 'Frequency Assessment', desc: 'We review your device datasheet to identify the applicable frequency bands and RF standards.' },
      { step: '02', icon: '🧪', title: 'RF Lab Testing', desc: 'We coordinate testing at a WPC-recognized lab to confirm compliance with DoT specifications.' },
      { step: '03', icon: '📤', title: 'Portal Filing', desc: 'Complete ETA application filed on the Saral Sanchar portal with test reports and technical documents.' },
      { step: '04', icon: '✅', title: 'ETA Granted', desc: 'WPC Wing reviews and issues your Equipment Type Approval, valid for 5 years.' },
    ],
    documents: [
      { icon: '📄', title: 'RF Test Report', desc: 'Valid RF test report from a WPC-recognized laboratory confirming compliance with DoT specifications.' },
      { icon: '📐', title: 'Technical Specification Sheet', desc: 'Datasheet covering operating frequency bands, modulation type, transmit power, and antenna gain.' },
      { icon: '📸', title: 'Product Photographs', desc: 'Clear photographs of the device from all angles including the label showing model number.' },
      { icon: '🏢', title: 'Company Registration Documents', desc: 'Certificate of Incorporation or equivalent business registration for the importing entity.' },
      { icon: '🚢', title: 'Import-Export Code (IEC)', desc: 'IEC certificate issued by DGFT — mandatory for all importers applying for WPC-ETA.' },
      { icon: '✅', title: 'Declaration of Conformity', desc: 'Self-declaration confirming the device complies with applicable technical standards.' },
    ],
    faqs: [
      { q: 'Which devices need WPC-ETA approval?', a: 'Any device using unlicensed radio frequency spectrum — including Wi-Fi, Bluetooth, Zigbee, Z-Wave, RFID, GPS modules, and wireless IoT devices — requires WPC-ETA approval before import.' },
      { q: 'Can I import wireless devices without WPC approval?', a: 'No. Importing wireless devices without WPC-ETA is illegal and the shipment will be detained at customs. The importer can also face penalties under the Indian Wireless Telegraphy Act.' },
      { q: 'How long is WPC-ETA approval valid?', a: 'WPC-ETA approvals are typically valid for 5 years from the date of issue and can be renewed before expiry to ensure continued compliance.' },
      { q: 'Do Indian-manufactured wireless devices also need WPC?', a: 'WPC-ETA is primarily for imports. Indian manufacturers need a manufacturing license under WPC rules for licensed spectrum devices. We assist with both scenarios.' },
      { q: 'What happens if my product fails RF testing?', a: 'We help identify the root cause — antenna design, power levels, or shielding issues — coordinate with your engineering team for fixes, and arrange re-testing at the earliest opportunity.' },
    ],
  },

  tec: {
    slug: 'tec',
    icon: '📶',
    title: 'TEC / MTCTE',
    subtitle: 'Telecom Engineering Centre',
    heroImage: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=1600&q=85&fit=crop',
    heroChips: ['MTCTE', 'TAC & IMEI', 'IoT Devices', 'Telecom Equipment', '0% Failure Rate'],
    intro: "Mandatory for telecom products under DoT — MTCTE (Mandatory Testing and Certification of Telecom Equipment) for routers, switches, SFPs, and network equipment.",
    introSecondary: 'Our TEC specialists manage lab testing at empanelled labs, prepare your MTCTE portal application, and coordinate with TEC until your certificate is issued.',
    quickInfo: [
      { label: 'Governing Body', value: 'TEC, Dept. of Telecom' },
      { label: 'Portal', value: 'MTCTE Portal (DoT)' },
      { label: 'Validity', value: '3 Years' },
      { label: 'Processing Time', value: '6–12 Weeks' },
      { label: 'Applicable To', value: 'All Telecom Equipment' },
    ],
    stats: [
      { value: '3 yrs', label: 'Certificate Validity', icon: '📅' },
      { value: '6–12', label: 'Weeks Timeline', icon: '⚡' },
      { value: 'Free', label: 'Initial Consultation', icon: '🆓' },
      { value: '0%', label: 'Failure Rate', icon: '❌' },
    ],
    types: [
      { icon: '📶', title: 'TEC/MTCTE Certification', tag: 'Mandatory', desc: 'Mandatory Testing & Certification of Telecom Equipment for all telecom products sold or used in India under DoT regulations.' },
      { icon: '📱', title: 'TAC & IMEI Registration', tag: 'Mobile Devices', desc: 'Type Allocation Code & IMEI registration for all mobile handsets and devices before launch or import into India.' },
      { icon: '🌐', title: 'IoT Device Certification', tag: 'IoT', desc: 'Certification for Internet of Things devices under the MTCTE framework including smart meters, asset trackers, and connected devices.' },
      { icon: '📡', title: 'Telecom Equipment Approval', tag: 'Telecom', desc: 'Approval for telecom network equipment, routers, switches, modems, and networking hardware under TEC standards.' },
    ],
    process: [
      { step: '01', icon: '🔍', title: 'Standard Identification', desc: 'We identify the applicable Essential Requirements and Indian telecom standard for your product category.' },
      { step: '02', icon: '🧪', title: 'Lab Testing', desc: 'Testing at a TEC-empanelled lab against all Essential Requirements of the applicable standard.' },
      { step: '03', icon: '📤', title: 'MTCTE Filing', desc: 'Complete application filed on the MTCTE portal with test reports and technical documentation.' },
      { step: '04', icon: '✅', title: 'Certificate Issued', desc: 'TEC reviews and issues your certification, valid for 3 years from the date of grant.' },
    ],
    documents: [
      { icon: '📄', title: 'Product Technical Datasheet', desc: 'Specification sheet covering model number, operating frequencies, power levels, and interfaces.' },
      { icon: '🧪', title: 'Test Report from TEC Lab', desc: 'Valid conformity test report from a TEC-designated or empanelled laboratory.' },
      { icon: '📐', title: 'Block Diagram of the Device', desc: 'Schematic showing internal architecture, RF components, and antenna design.' },
      { icon: '📸', title: 'Product Photographs', desc: 'Clear photographs including the rating label, connectivity ports, and antenna locations.' },
      { icon: '🏢', title: 'Company Registration & KYC', desc: "Certificate of Incorporation, GST, PAN, and KYC for the Indian applicant entity or IAR." },
      { icon: '✅', title: 'Declaration of Conformity', desc: 'Self-declaration confirming compliance with all applicable TEC Essential Requirements.' },
    ],
    faqs: [
      { q: 'What is MTCTE?', a: 'MTCTE stands for Mandatory Testing and Certification of Telecom Equipment. It is a DoT initiative requiring all telecom equipment sold or imported in India to be certified by TEC.' },
      { q: 'Which products fall under MTCTE?', a: 'Products include mobile phones, routers, switches, modems, set-top boxes, GPS devices, IoT equipment, and other telecom/networking hardware.' },
      { q: 'What is the penalty for selling uncertified telecom equipment?', a: 'Selling or importing uncertified telecom equipment can result in seizure, heavy penalties, and suspension of import license under the Indian Wireless Telegraphy Act and DoT regulations.' },
      { q: 'How long does TEC certification take?', a: 'Typically 6–12 weeks depending on product complexity, lab availability, and application completeness. We actively track your application to minimise delays.' },
      { q: 'Can foreign companies apply for MTCTE certification?', a: 'Yes. Foreign manufacturers can apply through an Indian Authorized Representative (IAR). We provide IAR services and manage the complete application process on your behalf.' },
    ],
  },

  bee: {
    slug: 'bee',
    icon: '⚡',
    title: 'BEE Registration',
    subtitle: 'Bureau of Energy Efficiency',
    heroImage: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&q=85&fit=crop',
    heroChips: ['Mandatory Star Rating', 'Voluntary Star Rating', 'Energy Certification', 'BEE Act Compliance', '0% Failure Rate'],
    intro: 'Star labelling and mandatory energy efficiency registration for appliances and equipment. Covers ACs, refrigerators, pumps, fans, motors, and 20+ more product categories.',
    introSecondary: 'Our BEE specialists coordinate energy testing at accredited labs, prepare your star label artwork, and manage the complete BEE portal registration and annual renewal.',
    quickInfo: [
      { label: 'Governing Body', value: 'Bureau of Energy Efficiency' },
      { label: 'Ministry', value: 'Power, Govt. of India' },
      { label: 'Validity', value: 'Annual' },
      { label: 'Processing Time', value: '4–8 Weeks' },
      { label: 'Applicable To', value: 'Home & Commercial Appliances' },
    ],
    stats: [
      { value: '20+', label: 'Product Categories', icon: '📋' },
      { value: '4–8', label: 'Weeks Timeline', icon: '⚡' },
      { value: 'Free', label: 'Initial Consultation', icon: '🆓' },
      { value: '0%', label: 'Failure Rate', icon: '❌' },
    ],
    types: [
      { icon: '⭐', title: 'Mandatory Star Rating', tag: 'Mandatory', desc: 'Compulsory BEE star labelling for ACs, refrigerators, washing machines, TVs, geysers, and more under the Energy Conservation Act.' },
      { icon: '🌟', title: 'Voluntary Star Rating', tag: 'Optional', desc: 'Optional BEE star label for products not yet under mandatory scheme — builds consumer trust and supports premium positioning.' },
      { icon: '🔌', title: 'Energy Efficiency Certification', tag: 'All Products', desc: 'BEE certification for energy-efficient products for public procurement under government schemes and green procurement policies.' },
      { icon: '🏭', title: 'BEE Act Compliance', tag: 'Compliance', desc: 'Complete BEE Act compliance management for manufacturers including annual submissions, audit support, and timely renewals.' },
    ],
    process: [
      { step: '01', icon: '🔍', title: 'Category Assessment', desc: 'We confirm whether your product falls under a mandatory or voluntary BEE star labelling category.' },
      { step: '02', icon: '🧪', title: 'Energy Testing', desc: 'Product tested at a BEE-accredited lab as per the applicable Indian Standard for energy consumption.' },
      { step: '03', icon: '📤', title: 'BEE Portal Registration', desc: 'Complete application filed on the BEE portal with test reports and label artwork.' },
      { step: '04', icon: '✅', title: 'Star Label Issued', desc: 'BEE approves your registration and star rating; annual renewal is tracked by our team.' },
    ],
    documents: [
      { icon: '🧪', title: 'Energy Test Report', desc: 'Valid test report from a BEE-accredited laboratory as per the applicable Indian Standard.' },
      { icon: '📐', title: 'Product Technical Specifications', desc: 'Datasheet covering model number, energy input/output ratings, and capacity.' },
      { icon: '🏷️', title: 'Brand & Model Details', desc: 'Brand name, model name and number, matching the test report and application form.' },
      { icon: '🏭', title: 'Manufacturing Unit Details', desc: 'Name, address, and registration details of the manufacturing or assembly unit.' },
      { icon: '🏢', title: 'Company KYC & Registration', desc: 'Certificate of Incorporation, PAN, GST registration, and signatory KYC.' },
      { icon: '🖼️', title: 'Label Artwork Proof', desc: 'Proposed BEE star label artwork meeting the prescribed format and specifications.' },
    ],
    faqs: [
      { q: 'Which appliances need mandatory BEE star labels?', a: 'Air conditioners, refrigerators, ceiling fans, washing machines, LED lamps, distribution transformers, water heaters, and several other categories are under mandatory BEE labelling.' },
      { q: 'Can I sell appliances without BEE star rating?', a: 'For mandatory categories, selling without a BEE star label is illegal and can result in seizure and penalties under the Energy Conservation Act.' },
      { q: 'How often must BEE registration be renewed?', a: 'BEE registrations must be renewed annually. The star rating may change as energy efficiency norms are upgraded periodically by the Bureau of Energy Efficiency.' },
      { q: 'Does BEE apply to imported products?', a: 'Yes, imported products in mandatory categories must also carry the BEE star label before being sold in India. We handle BEE compliance for both manufacturers and importers.' },
      { q: 'What is the timeline for getting BEE registration?', a: 'Typically 4–8 weeks from the time lab testing is complete and all documents are in order. We actively track and follow up with BEE to avoid unnecessary delays.' },
    ],
  },

  lmpc: {
    slug: 'lmpc',
    icon: '📦',
    title: 'LMPC Registration',
    subtitle: 'Legal Metrology Packaged Commodities',
    heroImage: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=1600&q=85&fit=crop',
    heroChips: ['Import License', 'Manufacturer Reg.', 'Label Compliance', 'Weights & Measures', '0% Failure Rate'],
    intro: 'Import licence and product label compliance under the Legal Metrology (Packaged Commodities) Rules. Mandatory for all importers selling pre-packaged goods in India.',
    introSecondary: 'Our LMPC specialists review your packaging artwork, prepare your complete application, and coordinate with the Controller of Legal Metrology until your licence is issued.',
    quickInfo: [
      { label: 'Governing Act', value: 'Legal Metrology Act, 2009' },
      { label: 'Authority', value: 'Controller of Legal Metrology' },
      { label: 'Validity', value: 'Annual Renewal' },
      { label: 'Processing Time', value: '2–4 Weeks' },
      { label: 'Applicable To', value: 'All Pre-Packaged Goods' },
    ],
    stats: [
      { value: 'Annual', label: 'Renewal Cycle', icon: '📅' },
      { value: '2–4w', label: 'Processing Time', icon: '⚡' },
      { value: 'Free', label: 'Initial Consultation', icon: '🆓' },
      { value: '0%', label: 'Failure Rate', icon: '❌' },
    ],
    types: [
      { icon: '📦', title: 'LMPC Import License', tag: 'Importers', desc: 'Mandatory for all importers of pre-packaged goods. Required before goods can be sold in India under the Legal Metrology (Packaged Commodities) Rules.' },
      { icon: '🏭', title: 'LMPC Manufacturer Registration', tag: 'Manufacturers', desc: 'For Indian manufacturers of pre-packaged commodities under the Packaged Commodities Rules, 2011.' },
      { icon: '📋', title: 'Packaged Commodity Registration', tag: 'Brand Owners', desc: 'Registration for brand owners and dealers dealing in packaged commodities across pan-India distribution.' },
      { icon: '⚖️', title: 'Legal Metrology Certification', tag: 'Weights & Measures', desc: 'Verification and certification of weighing and measuring instruments under Legal Metrology Act, 2009.' },
    ],
    process: [
      { step: '01', icon: '🔍', title: 'Applicability Check', desc: 'We confirm whether an import license or manufacturer registration applies to your business.' },
      { step: '02', icon: '🏷️', title: 'Label Compliance Review', desc: 'Your packaging artwork is reviewed against mandatory declarations required under the Rules.' },
      { step: '03', icon: '📤', title: 'Application Filing', desc: 'Complete application filed with the Controller of Legal Metrology along with all supporting documents.' },
      { step: '04', icon: '✅', title: 'Licence Issued', desc: 'Your LMPC registration or licence is granted; we track your annual renewal going forward.' },
    ],
    documents: [
      { icon: '📄', title: 'Company Registration & KYC', desc: 'Certificate of Incorporation, GST, PAN, and KYC for the Indian applicant entity.' },
      { icon: '📦', title: 'Import-Export Code (IEC)', desc: 'Mandatory for LMPC import license applications; must be active in the applicant\'s name.' },
      { icon: '🏷️', title: 'Product Packaging Samples & Labels', desc: 'Samples with all mandatory declarations visible — MRP, net quantity, and manufacturer details.' },
      { icon: '📋', title: 'Product List with HS Codes', desc: 'Complete list of SKUs with HS codes, net quantity, and category description.' },
      { icon: '📜', title: 'Brand Authorization Letter', desc: 'For importers selling under a foreign brand, confirming the right to import and sell in India.' },
      { icon: '🏭', title: 'Manufacturing License', desc: 'For manufacturer registration, a copy of the applicable factory license from the State authority.' },
    ],
    faqs: [
      { q: 'Who needs LMPC registration?', a: 'All importers, manufacturers, packers, and dealers of pre-packaged goods in India are required to obtain LMPC registration under the Legal Metrology (Packaged Commodities) Rules, 2015.' },
      { q: 'What must be declared on packaging?', a: 'Every pre-packaged product must declare: name of product, manufacturer name/address, net quantity, MRP (all-inclusive), month/year of manufacture, expiry date (if applicable), country of origin (for imports), and customer care details.' },
      { q: 'What is the penalty for non-compliance?', a: 'Selling without LMPC registration or non-compliant packaging can attract penalties up to ₹25,000 for the first offence and ₹50,000 for subsequent offences under the Legal Metrology Act.' },
      { q: 'Is LMPC required for all imported goods?', a: "Yes, any imported product that is pre-packaged and sold at retail level in India requires LMPC import license before it can be commercially sold." },
      { q: 'How long does LMPC registration take?', a: 'Typically 2–4 weeks from the date of complete application submission. We coordinate with the Controller of Legal Metrology and track your application at every stage.' },
    ],
  },

  iso: {
    slug: 'iso',
    icon: '🏆',
    title: 'ISO Certification',
    subtitle: 'International Management Systems',
    heroImage: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1600&q=85&fit=crop',
    heroChips: ['ISO 9001', 'ISO 14001', 'ISO 45001', 'ISO 27001', '0% Failure Rate'],
    intro: 'International management system certification for quality (9001), environment (14001), safety (45001), and information security (27001). We guide documentation, gap audits, and certification body liaison.',
    introSecondary: 'Our ISO consultants run your gap analysis, build your documentation from scratch or refine what you have, and liaise with the certification body through every audit stage.',
    quickInfo: [
      { label: 'Standards Covered', value: 'ISO 9001, 14001, 45001 & more' },
      { label: 'Recognition', value: 'Global (170+ Countries)' },
      { label: 'Validity', value: '3 Years + Annual Audit' },
      { label: 'Processing Time', value: '2–4 Months' },
      { label: 'Applicable To', value: 'All Industries & Sizes' },
    ],
    stats: [
      { value: '3 yrs', label: 'Certificate Validity', icon: '📅' },
      { value: '2–4', label: 'Months Timeline', icon: '⚡' },
      { value: 'Free', label: 'Initial Consultation', icon: '🆓' },
      { value: '0%', label: 'Failure Rate', icon: '❌' },
    ],
    types: [
      { icon: '🏆', title: 'ISO 9001:2015', tag: 'Most Popular', desc: "Quality Management System — the world's most recognized quality standard applicable to all industries and organization sizes." },
      { icon: '🌿', title: 'ISO 14001:2015', tag: 'Environment', desc: 'Environmental Management System for organizations committed to reducing environmental impact and meeting regulatory requirements.' },
      { icon: '🦺', title: 'ISO 45001:2018', tag: 'Safety', desc: 'Occupational Health & Safety Management System to proactively prevent workplace injuries, illness, and unsafe conditions.' },
      { icon: '🔒', title: 'ISO 27001:2022', tag: 'IT Security', desc: 'Information Security Management System for organizations handling sensitive data — increasingly required by enterprise clients.' },
      { icon: '🍽️', title: 'ISO 22000:2018', tag: 'Food Safety', desc: 'Food Safety Management System covering the entire food supply chain from farm to fork, recognized globally.' },
      { icon: '💉', title: 'ISO 13485:2016', tag: 'Medical Devices', desc: 'Quality Management System specifically for medical device manufacturers, suppliers, and distributors.' },
    ],
    process: [
      { step: '01', icon: '🔍', title: 'Gap Analysis', desc: 'We assess your current processes against the requirements of the chosen ISO standard.' },
      { step: '02', icon: '📝', title: 'Documentation Build', desc: 'We create or refine your quality manual, SOPs, and records needed to meet the standard.' },
      { step: '03', icon: '🔬', title: 'Certification Audit', desc: 'We liaise with the certification body through Stage 1 and Stage 2 audits.' },
      { step: '04', icon: '✅', title: 'Certificate Issued', desc: 'Your ISO certificate is issued, valid for 3 years with annual surveillance audits.' },
    ],
    documents: [
      { icon: '🏢', title: 'Company Registration Documents', desc: 'Certificate of Incorporation or equivalent document establishing your legal identity.' },
      { icon: '🗺️', title: 'Organizational Chart', desc: 'Current structure showing key functions, roles, and reporting lines.' },
      { icon: '📋', title: 'Existing Process Documents', desc: 'Any current SOPs or work instructions reviewed during gap analysis.' },
      { icon: '📊', title: 'Business Scope Description', desc: 'A clear description of products, services, and key processes for the scope statement.' },
      { icon: '🔖', title: 'Applicable Legal Requirements', desc: 'Relevant statutory requirements — mandatory for ISO 14001 and ISO 45001.' },
      { icon: '👥', title: 'Employee & Function Details', desc: 'Departments, key functions, and site locations to be covered under certification.' },
    ],
    faqs: [
      { q: 'Is ISO certification mandatory in India?', a: 'ISO certification is generally voluntary but is increasingly required for government tenders, international contracts, and export compliance. Some sectors have mandatory requirements.' },
      { q: 'How long does ISO certification take?', a: "Typically 2–4 months depending on your organization's size, existing processes, and the standard being pursued. We help expedite the process through structured gap analysis and documentation support." },
      { q: 'How long is an ISO certificate valid?', a: 'ISO certificates are valid for 3 years with annual surveillance audits in year 1 and year 2, and a recertification audit in year 3. We assist with all three cycles.' },
      { q: 'Can a small business get ISO certified?', a: 'Absolutely. ISO standards are designed to be scalable and apply to organizations of all sizes — from single-person businesses to large corporations across all industries.' },
      { q: 'Which ISO standard is right for my business?', a: 'It depends on your industry and goals. ISO 9001 suits most businesses for quality management. ISO 14001 is for environmental compliance, ISO 45001 for workplace safety, and ISO 27001 for data security. We can help you decide.' },
    ],
  },

  cdsco: {
    slug: 'cdsco',
    icon: '💊',
    title: 'CDSCO / Drug License',
    subtitle: 'Central Drugs Standard Control Organization',
    heroImage: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=1600&q=85&fit=crop',
    heroChips: ['Drug License', 'Cosmetic License', 'Medical Devices', 'DCGI Approval', '0% Failure Rate'],
    intro: 'Registration of medical devices, drugs, cosmetics, and diagnostics under CDSCO and MDR 2017. We manage the online portal, clinical evidence review, and CDSCO liaison.',
    introSecondary: 'Our CDSCO specialists prepare your technical dossier, coordinate with your Indian Authorized Agent, and manage every query raised by CDSCO or DCGI until approval.',
    quickInfo: [
      { label: 'Governing Body', value: 'CDSCO / DCGI' },
      { label: 'Governing Act', value: 'Drugs & Cosmetics Act, 1940' },
      { label: 'Device Rules', value: 'Medical Devices Rules 2017' },
      { label: 'Processing Time', value: '30 Days – 6 Months' },
      { label: 'Applicable To', value: 'Drugs, Cosmetics & Devices' },
    ],
    stats: [
      { value: '30d–6m', label: 'Processing Time', icon: '⚡' },
      { value: '3', label: 'Device Classes (B–D)', icon: '🔬' },
      { value: 'Free', label: 'Initial Consultation', icon: '🆓' },
      { value: '0%', label: 'Failure Rate', icon: '❌' },
    ],
    types: [
      { icon: '💊', title: 'Drug License', tag: 'Pharma', desc: 'Manufacturing or import license for pharmaceutical drugs and formulations under Drugs & Cosmetics Act.' },
      { icon: '💄', title: 'Cosmetic License', tag: 'Cosmetics', desc: 'Import or manufacturing license for cosmetic products sold in India under CDSCO regulations.' },
      { icon: '🔬', title: 'Medical Device Registration', tag: 'Medical', desc: 'Registration for medical devices including Class A, B, C & D devices under MDR 2017.' },
      { icon: '📋', title: 'CDSCO Import License', tag: 'Imports', desc: 'Import license for drugs, cosmetics and medical devices under Form 10 / Form 8 procedures.' },
      { icon: '🏥', title: 'DCGI Approval', tag: 'New Drugs', desc: 'Approval from Drug Controller General of India for new drugs, biologicals and clinical trials.' },
      { icon: '🧪', title: 'Clinical Trial Approval', tag: 'Research', desc: 'CDSCO approval for conducting clinical trials in India for new drugs and medical devices.' },
    ],
    process: [
      { step: '01', icon: '🔍', title: 'Classification Review', desc: 'We determine the exact CDSCO category and device class applicable to your product.' },
      { step: '02', icon: '📑', title: 'Dossier Preparation', desc: 'We prepare your complete CTD-format technical dossier with quality and clinical data.' },
      { step: '03', icon: '📤', title: 'CDSCO Portal Filing', desc: 'Application filed via the Indian Authorized Agent along with GMP and CoPP documentation.' },
      { step: '04', icon: '✅', title: 'License Granted', desc: 'CDSCO/DCGI reviews and issues your registration or import license.' },
    ],
    documents: [
      { icon: '📄', title: 'Company Registration & KYC', desc: 'Certificate of Incorporation, GST, PAN, and KYC for the Indian Authorized Agent entity.' },
      { icon: '📑', title: 'Technical Dossier (CTD Format)', desc: 'Complete Common Technical Document covering quality, non-clinical, and clinical data.' },
      { icon: '🏭', title: 'GMP Certificate', desc: 'Issued by the national regulatory authority of the manufacturing country.' },
      { icon: '📜', title: 'Certificate of Pharmaceutical Product', desc: 'Confirming the product is authorized for sale in the country of manufacture.' },
      { icon: '🔬', title: 'Clinical / Safety Data', desc: 'As required for new drugs, new combinations, and biological products.' },
      { icon: '📊', title: 'Stability Data', desc: 'Demonstrating quality and safety throughout the claimed shelf life.' },
    ],
    faqs: [
      { q: 'Is CDSCO approval required for all drugs imported into India?', a: "Yes, all drugs imported into India require either a registration certificate or import license from CDSCO/DCGI. The requirement varies by drug category and whether it's already approved in India." },
      { q: 'What is the difference between CDSCO and DCGI?', a: 'CDSCO (Central Drugs Standard Control Organization) is the regulatory body. DCGI (Drug Controller General of India) is its head. Approvals for new drugs, clinical trials, and certain imports require DCGI approval.' },
      { q: 'How long does medical device registration take?', a: 'Class A and B devices typically take 30–90 days. Class C and D devices take 3–6 months. We help prepare error-free dossiers to avoid rejection or delays.' },
      { q: 'Do cosmetics need CDSCO approval?', a: 'Yes, cosmetics imported into India require a CDSCO import license. Products like hair dyes, sunscreens, and anti-dandruff shampoos are treated as drugs and need drug license.' },
      { q: 'Can a foreign manufacturer apply directly for CDSCO approval?', a: 'Foreign manufacturers must appoint an Indian Authorized Agent (IAA) to apply on their behalf. We provide authorized agent services and manage the complete regulatory process end-to-end.' },
    ],
  },
};

export const SERVICE_SLUGS = Object.keys(SERVICE_DETAILS);
